# Lingmo Forge Official Preset Configuration
# 官方预设 - 用于标准 ISO 构建

arch = "amd64"
suite = "trixie"

[platform]
name = "debian"
components = ["main", "contrib", "non-free", "non-free-firmware"]

[image]
engine = "livebuild"
iso_name = "lingmo-live-amd64.iso"
volume_id = "Lingmo Live AMD64"

[[repositories]]
name = "lingmoos-obs"
uri = "https://download.opensuse.org/repositories/home:/LingmoOS/Debian_13/"
suite = "./"
signed_by = "/etc/apt/keyrings/lingmo.gpg"
enabled = true
